/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/bundle-optimizer
declare module '*?async' {
  const component: any
  export = component
}
declare module '@/subEcharts/echarts/components/BarChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/BarChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/DonutChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/DonutChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/FunnelChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/FunnelChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/GaugeChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/GaugeChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/LineChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/LineChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/LiquidFillChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/LiquidFillChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/MiniLineChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/MiniLineChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/PieChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/PieChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/ScatterChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/ScatterChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/StackedBarChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/StackedBarChart.vue')
  export = component
}
declare module '@/subEcharts/echarts/components/RadarChart.vue?async' {
  const component: typeof import('@/subEcharts/echarts/components/RadarChart.vue')
  export = component
}
