/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./../components/layout/BaseLayout.vue')['default']
    Calendar: typeof import('./../components/common/Calendar.vue')['default']
    DemoBlock: typeof import('./../components/DemoBlock.vue')['default']
    GlobalLoading: typeof import('./../components/common/GlobalLoading.vue')['default']
    GlobalMessage: typeof import('./../components/common/GlobalMessage.vue')['default']
    GlobalToast: typeof import('./../components/common/GlobalToast.vue')['default']
    PrivacyPopup: typeof import('./../components/business/PrivacyPopup.vue')['default']
  }
}
